name: Subdir to Repository

on:
  workflow_dispatch:
  schedule:
    - cron: "59 4 * * *" #daily (UTC)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Run Subdir to Repository Script
      run: |
        chmod +x subdir_to_repository.sh
        ./subdir_to_repository.sh

    - name: Push to Repository
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add .
        git commit -m "Automated update"
        git push https://${{ secrets.GH_PAT }}@github.com/your-org/your-repo.git HEAD:main

